<?php

namespace Jazzyweb\CursoSf2\ElORMDoctrineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeliculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeliculaRepository extends EntityRepository {

    public function findByActorId($actor_id) {

        // Todas las películas del actor con id=1
        $query = $this->getEntityManager()->createQuery(
                        'SELECT p FROM JCSf2ORMDoctrineBundle:Pelicula p 
                         JOIN p.actores a
                         WHERE a.id = :actor_id'
                )->setParameter('actor_id', $actor_id);

        return $query->getResult();
    }

    public function findByActorNombreLike($patron) {
        // Todas las películas en las que hay algún actor cuyo nombre es como JOHN%
        $query = $this->getEntityManager()->createQuery(
                        'SELECT p FROM JCSf2ORMDoctrineBundle:Pelicula p 
                         JOIN p.actores a
                         WHERE a.nombre LIKE :patron'
                )->setParameter('patron', $patron);

        return $query->getResult();
    }

}
