parameters:
#    jc_sf2_fundamentos.example.class: Jazzyweb\CursoSf2\LosFundamentosBundle\Example

services:
#    jc_sf2_fundamentos.example:
#        class: %jc_sf2_fundamentos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     generador.datos:
       class: Jazzyweb\CursoSf2\LosFundamentosBundle\Services\GeneradorDatosService

