jc_sf2_control_rutas:
    resource: "@JCSf2ControlRutasBundle/Resources/config/routing.yml"
    prefix: /controladoresyrutas

homepage:
    pattern: /
    defaults: { _controller: JCSf2TemplatesBundle:Default:inicio }

jc_sf2_seguridad:
    resource: "@JCSf2SeguridadBundle/Resources/config/routing.yml"
    prefix: /seguridad

jc_sf2_orm_doctrine:
    resource: "@JCSf2ORMDoctrineBundle/Resources/config/routing.yml"
    prefix: /doctrine

jc_sf2_valy_forms:
    resource: "@JCSf2ValyFormsBundle/Resources/config/routing.yml"
    prefix: /valyforms

jc_sf2_los_servicios:
    resource: "@JCSf2LosServiciosBundle/Resources/config/routing.yml"
    prefix: /services

jc_sf2_templates:
    resource: "@JCSf2TemplatesBundle/Resources/config/routing.yml"
    prefix: /templates

jc_sf2_fundamentos:
    resource: "@JCSf2FundamentosBundle/Resources/config/routing.yml"
    prefix: /fundamentos