jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    juanda: {password: juanda, roles: [ 'ROLE_ADMIN', 'ROLE_REDACTOR' ]}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        area_nosegura:
            pattern:  ^/seguridad/(nosegura|login)
            security: false
            
        area_segura:
            pattern:    ^/seguridad/
            form_login:                
                login_path: jc_sf2_seguridad_login
                check_path: jc_sf2_seguridad_login_check
                
            logout:
                path:   jc_sf2_seguridad_logout
                target: jc_sf2_seguridad_no_segura
           

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/seguridad/admin, roles: ROLE_ADMIN }
        - { path: ^/seguridad/redaccion, roles: ROLE_REDACTOR }
