jc_sf2_seguridad_homepage:
    pattern:  /
    defaults: { _controller: JCSf2SeguridadBundle:Default:index }

jc_sf2_seguridad_login:
    pattern:   /login
    defaults:  { _controller: JCSf2SeguridadBundle:Default:login }
    
jc_sf2_seguridad_login_check:
    pattern:   /check_signin

jc_sf2_seguridad_logout:
    pattern: /logout
   
jc_sf2_seguridad_admin:
    pattern:  /admin
    defaults: { _controller: JCSf2SeguridadBundle:Default:admin }
    
jc_sf2_seguridad_redaccion:
    pattern:  /redaccion
    defaults: { _controller: JCSf2SeguridadBundle:Default:redaccion }

jc_sf2_seguridad_no_segura:
    pattern:  /nosegura
    defaults: { _controller: JCSf2SeguridadBundle:Default:noSegura }

jc_sf2_seguridad_encoder:
    pattern:  /encoder
    defaults: { _controller: JCSf2SeguridadBundle:Default:encoder }


