parameters:
    jc_sf2_seguridad.customuser.class: Jazzyweb\CursoSf2\LaSeguridadBundle\CustomUserProvider\UserProvider

services:
    jc_sf2_seguridad.customuser:
        class: %jc_sf2_seguridad.customuser.class%

    custom.security.authentication.provider:
        class:  Jazzyweb\CursoSf2\LaSeguridadBundle\CustomAuthenticationProvider\Provider
        arguments: [""]

    custom.security.authentication.listener:
        class:  Jazzyweb\CursoSf2\LaSeguridadBundle\CustomAuthenticationProvider\Listener
        arguments: ["@security.context", "@security.authentication.manager"]

    jc_sf2_seguridad.password_resetting:
        class: Jazzyweb\CursoSf2\LaSeguridadBundle\FOSListeners\ChangePasswordListener
        arguments: [@router]
        tags:
           - { name: kernel.event_subscriber }

#    jc_sf2_seguridad.access.blacklist_voter:
#        class:      Jazzyweb\CursoSf2\LaSeguridadBundle\Authorization\ClientIpVoter
#        arguments:  ["@service_container", [123.123.123.123, 171.171.171.171, 127.0.0.1]]
#        public:     false
#        tags:
#           - { name: security.voter }
