parameters:
    jc_sf2_seguridad.customuser.class: Jazzyweb\CursoSf2\LaSeguridadBundle\CustomUser\UserProvider

services:
    jc_sf2_seguridad.customuser:
        class: %jc_sf2_seguridad.customuser.class%
