parameters:
#    jc_sf2_seguridad.example.class: Jazzyweb\CursoSf2\LaSeguridadBundle\Example

services:
#    jc_sf2_seguridad.example:
#        class: %jc_sf2_seguridad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
