parameters:
#    jc_sf2_orm_doctrine.example.class: Jazzyweb\CursoSf2\ElORMDoctrineBundle\Example

services:
#    jc_sf2_orm_doctrine.example:
#        class: %jc_sf2_orm_doctrine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
