jc_sf2_valy_forms_homepage:
    pattern:  /
    defaults: { _controller: JCSf2ValyFormsBundle:Default:index }

jc_sf2_valy_forms_validacion:
    pattern:  /validacion
    defaults: { _controller: JCSf2ValyFormsBundle:Validacion:validacion }

jc_sf2_valy_forms_validacion_directa:
    pattern:  /validacion_directa
    defaults: { _controller: JCSf2ValyFormsBundle:Validacion:validacionDirecta }
    
jc_sf2_valy_forms_formularios:
    pattern:  /formularios
    defaults: { _controller: JCSf2ValyFormsBundle:Formularios:index }
    
jc_sf2_valy_forms_formularios_en_controlador:
    pattern:  /formularios/en/controlador
    defaults: { _controller: JCSf2ValyFormsBundle:Formularios:enControlador }

jc_sf2_valy_forms_formularios_en_su_clase:
    pattern:  /formularios/en/su/clase
    defaults: { _controller: JCSf2ValyFormsBundle:Formularios:enSuPropiaClase }

jc_sf2_valy_forms_formularios_envio:
    pattern:  /formularios/envio
    defaults: { _controller: JCSf2ValyFormsBundle:Formularios:envio }

jc_sf2_valy_forms_formularios_tiposwidgets:
    pattern:  /formularios/tipos/de/widgets
    defaults: { _controller: JCSf2ValyFormsBundle:Formularios:tiposDeWidgets }